version: '3.8'

services:
  dasp-rust:
    build:
      context: rust
      dockerfile: Dockerfile
    command: ['test']
    container_name: dasp-rust

  dasp-c:
    build:
      context: c
      dockerfile: Dockerfile
    command: ['test']
    container_name: dasp-c

  dasp-cuda:
    build:
      context: .
      dockerfile: cuda/Dockerfile
    command: ['test']
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: dasp-cuda
